# Generated by Django 3.1.3 on 2021-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210515_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
