# Generated by Django 3.1.3 on 2021-05-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210515_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seat',
            new_name='seats',
        ),
        migrations.RenameField(
            model_name='seats',
            old_name='seat',
            new_name='seatno',
        ),
    ]
